<footer>
    <div class="footer-columns">
        <div class="footer-column">
            <h1>Contact us</h1>
            <div class="footer-links">
                <ul>
                    <li>Phone</li>
                    <li><a href="mailto:104527639@student.swin.edu.au">Email</a></li>
                    <li><a href="https://www.google.com/maps/place/Swinburne+University+of+Technology/@-37.8221504,145.0389546,15z/data=!4m6!3m5!1s0x6ad642326bae5aaf:0x75e96bbd4988f769!8m2!3d-37.8221504!4d145.0389546!16zL20vMDFrcV9z?entry=ttu">Office</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-column">
            <h1>About us</h1>
            <div class="footer-links">
                <ul>
                    <li><a href="jobs.php">Career</a></li>
                    <li><a href="about.php">Introducing us</a></li>
                    <li><a href="index.php">News</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-column">
            <h1>Follow us</h1>
            <div class="footer-links">
                <ul>
                    <li><a href="https://www.facebook.com">Facebook</a></li>
                    <li><a href="https://www.instagram.com">Instagram</a></li>
                    <li><a href="https://youtu.be/0VD9kKF6Kh8">Youtube</a></li>
                </ul>
            </div>
        </div>
    </div>
    <br>
    <hr>
    <br>
    <div class="email-link">
        <a href="mailto:104527639@student.swin.edu.au">Our EMAIL here!</a>
    </div>
    <div class="youtube-link">
        <a href="https://youtu.be/NqPIJThhGYo">Our Assignment 2 YOUTUBE video!</a>
    </div>
    <br>
</footer>