<!-- Beginning: Nav -->
  <div id="main">
    <div id="header">
      <ul id="nav">
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="about.php">About Us</a></li>
        <li><a href="login.php">Login</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>
        <li><a href="phpenhancements.php">PHP enhancements</a></li>
      </ul>
  <!-- Ending: Nav -->
  <!-- Beginning: Search button -->
      <div class="search-button">
        <span class="search-icon ti-search"></span>
  <!-- Ending: Search button -->
      </div>
    </div>